In [44]:
import torch
import numpy as np

In [21]:
x = torch.empty(2)
x = torch.empty(2, 2, 3)
print(x) # values are uninitialised
print(x.size())

tensor([[[2.1304e+12, 3.0763e-41, 1.8784e+12],
         [3.0763e-41, 1.1210e-43, 0.0000e+00]],

        [[8.9683e-44, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 2.1299e+12, 3.0763e-41]]])
torch.Size([2, 2, 3])


In [11]:
x = torch.rand(2, 2)
x

tensor([[0.1076, 0.6804],
        [0.5216, 0.6133]])

In [13]:
x = torch.zeros(2, 2)
x

tensor([[0., 0.],
        [0., 0.]])

In [15]:
x = torch.ones(2, 2)
x

tensor([[1., 1.],
        [1., 1.]])

In [22]:
x = torch.ones(2, 2) # float32
x = torch.ones(2, 2, dtype=torch.int)
x = torch.ones(2, 2, dtype=torch.double) # float64
x = torch.ones(2, 2, dtype=torch.float16)
print(x.dtype)

torch.float16


In [24]:
# create from list
x = torch.tensor([2.5, 0.1])
x

tensor([2.5000, 0.1000])

In [33]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

z = x + y # eltwise
print(z)

z = torch.add(x, y) # also eltwise
print(z)

y.add_(x) # functions with trailing underscores work in place
print(y)

z = x - y # torch.sub(x, y), y.sub_(x)
print(z)

z = x * y # torch.mul(x, y), y.mul_(x)
print(z)

z = x  / y # torch.div(x, y), y.div_(x)
print(z)

tensor([[0.5485, 0.0863],
        [0.6505, 0.0135]])
tensor([[0.2063, 0.6991],
        [0.6515, 0.7297]])
tensor([[0.7547, 0.7855],
        [1.3020, 0.7433]])
tensor([[0.7547, 0.7855],
        [1.3020, 0.7433]])
tensor([[0.7547, 0.7855],
        [1.3020, 0.7433]])
tensor([[-0.2063, -0.6991],
        [-0.6515, -0.7297]])
tensor([[0.4139, 0.0678],
        [0.8470, 0.0101]])
tensor([[0.7267, 0.1099],
        [0.4996, 0.0182]])


In [38]:
# Slicing
x = torch.rand(5, 3)
print(x)
print(x[:, 0]) # all rows for column 0
print(x[1, :]) # all cols for 2nd row
print(x[1,1])
print(x[1,1].item())  # tensors with 1 element have a .item() method

tensor([[0.0855, 0.7053, 0.3198],
        [0.9366, 0.6046, 0.6927],
        [0.3896, 0.9030, 0.0279],
        [0.8220, 0.2443, 0.5046],
        [0.4608, 0.0803, 0.5712]])
tensor([0.0855, 0.9366, 0.3896, 0.8220, 0.4608])
tensor([0.9366, 0.6046, 0.6927])
tensor(0.6046)
0.6045728921890259


In [43]:
# Reshaping
x = torch.rand(4, 4)
print(x)

y = x.view(16) # 1d
print(y)
print(y.size())

y = x.view(-1, 8) # -1 means infer the size
print(y.size())

tensor([[0.2703, 0.1382, 0.3164, 0.2121],
        [0.7946, 0.6832, 0.9260, 0.8544],
        [0.9761, 0.8947, 0.2375, 0.3727],
        [0.2394, 0.7658, 0.4770, 0.5699]])
tensor([0.2703, 0.1382, 0.3164, 0.2121, 0.7946, 0.6832, 0.9260, 0.8544, 0.9761,
        0.8947, 0.2375, 0.3727, 0.2394, 0.7658, 0.4770, 0.5699])
torch.Size([16])
torch.Size([2, 8])


In [53]:
# To / from numpy
a = torch.ones(5)
print(a)

b = a.numpy() # is a view to the same memory as a when on CPU
print(type(b))

a.add_(1)
print(a)
print(b)


a = np.ones(5)
print(a)
b = torch.from_numpy(a) # also a view to same memory, float64 by default
print(b)

a +=1
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [54]:
# CUDA
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device=device)

    z = x + y

    # z.numpy() # won't work, need to move it back to the CPU first
    z = z.to('cpu')


/home/craigc/miniconda3/envs/obb/lib/python3.9/site-packages/torch/cuda/__init__.py:145: UserWarning: 
NVIDIA GeForce RTX 3080 Ti with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA GeForce RTX 3080 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))


RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.